sudo: required
services:
  - docker

before_install:
  - docker build -t brinduc/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true brinduc/react-test npm test
  
after_success:
  - docker build -t brinduc/multi-client ./client
  - docker build -t brinduc/multi-nginx ./nginx
  - docker build -t brinduc/multi-server ./server
  - docker build -t brinduc/multi-worker ./worker