sudo: required
services:
  - docker

before_install:
  - docker build -t brinduc/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true brinduc/react-test npm test
  
after_success:
  - docker build -t brinduc/multi-client ./client
  - docker build -t brinduc/multi-nginx ./nginx
  - docker build -t brinduc/multi-server ./server
  - docker build -t brinduc/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  # Take those images and push to dockerhub
  - docker push brinduc/multi-client
  - docker push brinduc/multi-nginx
  - docker push brinduc/multi-server
  - docker push brinduc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "muli-docker"
  env: "Mulidocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-028058238784"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"